# Generated by Django 4.1.4 on 2022-12-08 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("departamentos", "0001_initial"),
        ("empresas", "0001_initial"),
        ("funcionarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="departamentos",
            field=models.ManyToManyField(to="departamentos.departamento"),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="empresa",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="empresas.empresa",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="funcionario",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
