# Generated by Django 4.1.4 on 2022-12-08 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0002_funcionario_departamentos_funcionario_empresa_and_more"),
        ("documentos", "0002_documento_autor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="autor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="funcionarios.funcionario",
            ),
            preserve_default=False,
        ),
    ]
